### PR TITLE
Add multi-character delimiter support

### PR DESCRIPTION
**Pull request by vedran-m**

### CODE REVIEW

**Comment by vedran-m** [comment]
Conformed my formatting a bit so it's closer to the rest of the code.

**Comment by 22222** [comment]
Thanks for the pull request!

That seems like a reasonable feature to add, especially since the VB parser does support it.  I originally left it as a single character because I didn't have any need for a longer delimiter and I was worried about too much complexity being added.  But at a quick glance of the code it doesn't look like things got very much more complicated.

I did run a quick test run using a version of the `ComparisonWithVbTextFieldParserTest.RandomInput` unit test with a two-character delimiter, like:

```c#
expectedParser.SetDelimiters(",,");
actualParser.SetDelimiter(",,");
```

And it looks like that did find some differences between this parser and the VB one.  It might be some weird behavior of the VB parser for some input, but it's kind of tedious to track down the root of the problem from those random input tests.

So I'll do some more research on that, and also review the code changes more thoroughly.

**Comment by vedran-m** [comment]
Looks like a bug with how `6,,,` is parsed, due to this:
```
            // If the last char is the delimiter, then we need to add an extra empty field.
            if (line.Length == 0 || IsEndingEqualToDelimiter(line))
            {
                fields.Add(string.Empty);
            }
```

Will try to fix it.

**Comment by vedran-m** [comment]
Found a hardcoded comma in the original code as well, the same test didn't pass for anything other than a comma as a delimiter:
```
if (i < 0)
{
    line += ',';
    i = line.Length - 1;
}
```
 
Should be working fine after latest changes.

**Comment by vedran-m** [comment]
Added another fix for how double quote as delimiter is handled.
Think I'm done for now - it handles all cases I've had issues with :)

**Comment by 22222** [comment]
Thanks for the additional work.

I merged this into a feature branch for now and added some more tests.  Once I get all of the tests passing (and maybe add a few more tests), I'll merge it into the master branch and put it in a release.

**Pull request merged**
